# Generated by Django 3.2.9 on 2024-01-30 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('author_name', models.CharField(default='unknown', max_length=100)),
                ('author_wiki_link', models.TextField(blank=True, max_length=1200)),
                ('author_wiki_link_d', models.TextField(blank=True, max_length=1200)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('wiki_idx', models.CharField(blank=True, max_length=10)),
                ('author_wiki_img', models.URLField(blank=True, max_length=300)),
                ('user_num_a', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date_add_author')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='date_update_author')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_music_1', models.URLField(blank=True, max_length=100, null=True)),
                ('type_music_1', models.CharField(blank=True, max_length=6, null=True)),
                ('link_music_2', models.URLField(blank=True, max_length=100, null=True)),
                ('type_music_2', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_poster_1', models.URLField(blank=True, max_length=100, null=True)),
                ('link_poster_2', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_video', models.URLField(blank=True, max_length=100, null=True)),
                ('type_video', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(blank=True, help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default='unknown', max_length=320, null=True)),
                ('google_id', models.CharField(default='', max_length=24)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('author_wiki_idx', models.CharField(blank=True, max_length=10)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('published', models.DateField(blank=True, null=True)),
                ('category', models.CharField(default='unknown', max_length=48)),
                ('summary', models.TextField(default='no description', max_length=1200)),
                ('isbn', models.CharField(max_length=24, verbose_name='ISBN')),
                ('language', models.CharField(blank=True, choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], max_length=12)),
                ('epub', models.CharField(blank=True, max_length=10, verbose_name='EPUB')),
                ('embeddable', models.CharField(blank=True, max_length=14)),
                ('imageLinks', models.URLField(default='http://books.google.com/books/content?id=YS7eSh0hbDEC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', max_length=300)),
                ('preview_link', models.URLField(default='no new book preview link', max_length=300)),
                ('preview_link_new', models.URLField(blank=True, default='no new book preview link', max_length=300)),
                ('selfLink', models.URLField(blank=True, default='no google apis json link')),
                ('user_num_b', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date add book')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='date update book')),
                ('slug', models.SlugField(blank=True, default='unknown', max_length=320, null=True)),
                ('url_pdf', models.CharField(blank=True, default='unknown', max_length=320, null=True)),
                ('url_pdf_search', models.CharField(blank=True, default='unknown', max_length=320, null=True)),
                ('pdf_search_filename', models.CharField(blank=True, default='unknown', max_length=120, null=True)),
                ('url_libgen', models.CharField(blank=True, default='unknown', max_length=120, null=True)),
                ('author_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_author', related_query_name='book_author', to='booksmart.author')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'surname'],
            },
        ),
    ]
