# Generated by Django 3.2.9 on 2024-01-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksmart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_search_filename',
            field=models.CharField(blank=True, default='unknown', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default='unknown', max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(blank=True, default='unknown', max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='url_libgen',
            field=models.CharField(blank=True, default='unknown', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='url_pdf',
            field=models.CharField(blank=True, default='unknown', max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='url_pdf_search',
            field=models.CharField(blank=True, default='unknown', max_length=320, null=True),
        ),
    ]
