# Generated by Django 3.2.9 on 2023-09-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksmart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(default='unknown', max_length=48),
        ),
    ]
