# Generated by Django 3.2.9 on 2023-12-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksmart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='booksmart_book',
        ),
        migrations.AddField(
            model_name='book',
            name='url_pdf_search',
            field=models.URLField(blank=True, default='no pdf links', null=True),
        ),
    ]
