# Generated by Django 3.2.9 on 2023-12-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksmart', '0002_auto_20231220_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='url_pdf',
            field=models.CharField(blank=True, default='no pdf link', max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='url_pdf_search',
            field=models.CharField(blank=True, default='no pdf links', max_length=320, null=True),
        ),
    ]
