# Generated by Django 3.2.9 on 2023-12-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksmart', '0003_auto_20231220_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_search_filename',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='url_pdf_search',
            field=models.CharField(blank=True, default='', max_length=320, null=True),
        ),
    ]
