# Generated by Django 3.2.9 on 2023-12-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksmart', '0004_auto_20231220_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='url_pdf',
            field=models.CharField(blank=True, default='', max_length=320, null=True),
        ),
    ]
