# Generated by Django 3.2.9 on 2024-01-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksmart', '0005_alter_book_url_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url_libgen',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
