# Generated by Django 3.2.9 on 2023-09-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230904_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_email_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='EmailConfirmationToken',
        ),
    ]
